#!/bin/sh

touch /etc/config/zzuportal
uci -q get zzuportal.main >/dev/null || uci set zzuportal.main=main
uci -q get zzuportal.main.enabled >/dev/null || uci set zzuportal.main.enabled=0
uci -q get zzuportal.main.type >/dev/null || uci set zzuportal.main.type=0
uci -q get zzuportal.main.isp >/dev/null || uci set zzuportal.main.isp=zzuwlan
uci -q get zzuportal.main.check_host >/dev/null || uci set zzuportal.main.check_host='223.5.5.5'
uci -q get zzuportal.main.check_interval >/dev/null || uci set zzuportal.main.check_interval=10
uci -q get zzuportal.main.mac_settle_delay >/dev/null || uci set zzuportal.main.mac_settle_delay=3
uci -q get zzuportal.main.login_url >/dev/null || uci set zzuportal.main.login_url='http://172.16.2.9:801/eportal/portal/login?callback=dr1004&login_method=1'
uci -q get zzuportal.main.logout_url >/dev/null || uci set zzuportal.main.logout_url='http://172.16.2.9:801/eportal/portal/mac/unbind?callback=dr1002'
uci -q get zzuportal.main.info_url >/dev/null || uci set zzuportal.main.info_url='http://172.16.2.9:801/eportal/portal/custom?callback=dr1002'

uci commit zzuportal
chmod 0755 /etc/zzuportal/*.sh
chmod 0755 /usr/bin/zzuportal
/etc/init.d/zzuportal enable
exit 0
